---
- include: user.yml

- name: Change the login with pubkey parameter to "yes"
  lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: '^#?PubkeyAuthentication' 
    line: 'PubkeyAuthentication yes' 
  notify:
    - reload sshd

- name: Add your packages
  apt:
    state: latest
    update_cache: "yes"
    pkg:
      - git
      - tmux
      - screen
      - wget
      - curl
      - vim
      - htop
      - net-tools
      - unzip
      - python-apt