---

- name: Setup azerothcore
  include_tasks: setup.yml


- name: WoWcloud up
  debug: 
    msg: "Dummy task for starting WoWCloud"
  notify: "Start wowcloud"


#azerothcore up (handler)
#create users from vault
#update realmlist (handler?)
#restart azerothcore
...