---
#clone repo

- name: Check if the repo exists
  stat:
    path: "/home/{{ wowcloud_user }}/wowcloud"
  register: stat_wowcloudrepo


- name: Clone wowcloud repo
  git:
    repo: "{{ wowcloud_repo }}" 
    dest: /home/{{ wowcloud_user }}/wowcloud
    version: "{{ wowcloud_version }}"
  when: stat_wowcloudrepo.stat.exists == False

- name: Check if assets exist
  stat:
    path: "/home/{{ wowcloud_user }}/wowcloud/assets.zip"
  register: stat_wowassets

- name: Download assets
  get_url:
    url: '{{ wowcloud_assets }}'
    dest: "/home/{{ wowcloud_user }}/wowcloud/assets.zip"
  when: 
    - stat_wowcloudrepo.stat.exists
    - stat_wowassets.stat.exists == False

- name: Unzip assets
  unarchive:
    src: "/home/{{ wowcloud_user }}/wowcloud/assets.zip"
    dest: "/home/{{ wowcloud_user }}/wowcloud/docker/worldserver/data/"
    remote_src: yes
    keep_newer: yes
  when: stat_wowcloudrepo.stat.exists == true

- name: Generate server config
  command: "sh /home/{{ wowcloud_user }}/wowcloud/bin/acore-docker-generate-etc"
  args:
    chdir: /home/{{ wowcloud_user }}/wowcloud

- name: Compile wowcloud
  command: "sh /home/{{ wowcloud_user }}/wowcloud/bin/acore-docker-build"
  args:
    chdir: /home/{{ wowcloud_user }}/wowcloud


...