---
- name: Install required packages
  apt:
    name:
    - ca-certificates

- name: Install python-pip
  apt:
    state: latest
    update_cache: "yes"
    pkg:
      - python-pip

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository 
  apt_repository:
    filename: docker
    repo: '{{ docker_repo }}'
    state: present
    
- name: Install docker
  apt:
    pkg: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    update_cache: "yes"
  notify: "start-enable-docker"

- name: Install docker Compose
  include_tasks: setup-docker-compose.yml


