---
- name: Install required packages
  apt:
    name:
    - ca-certificates

- name: Install python-pip
  apt:
    name: "{{ packages }}"
    update_only: yes
  vars:
    packages:
    - python-pip

- name: Add docker repository 
  apt_repository:
    filename: docker
    description: docker-ce repository
    repo: '{{ docker_repo }}'
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    
- name: Install docker
  apt:
    name: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
  notify: "start-enable-docker"

- name: Install docker Compose
  include_tasks: setup-docker-compose.yml


