---
- hosts: all
  become: true
  gather_facts: true

  pre_tasks:
  - name: Install python for Ansible for yum based distros
    raw: bash -c "test -e /usr/bin/python || (yum -y update && yum -y install python)"
    register: output
    changed_when: output.stdout != ""
    become: true
    tags:
        - always
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    
  - name: Install python for Ansible for apt based distros
    raw: bash -c "test -e /usr/bin/python || (apt -y update && apt -y install python)"
    register: output
    changed_when: output.stdout != ""
    become: true
    tags:
        - always
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  
  - import_playbook: "playbooks/{{ env }}.yml"
...